### ISSUE TITLE
Stream MP3 audio from S3/Cloudfront

### ISSUE THREAD

**Issue by aiwilliams** [wfth/online#1]
Visitors want to stream audio in the browser. We need to figure out how that is going to work.

- [x] review https://aws.amazon.com/cloudfront/streaming/
- [x] test the [JWPlayer](http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/TutorialStreamingJWPlayer.html)
- [x] load the plugin in the major desktop and mobile browsers and stream a single `.mp3` file
- [x] consider other recommended streaming plugins if JWPlayer doesn't work

I expect that the output of this task will be an `.html` file in this repository that we can demonstrate to the team. DO NOT include any AWS secrets in the assets committed to this repository; for now the S3 resources should be world readable.

**Comment by isaacjwilliams** [comment]
1. Create an S3 bucket
2. Upload sermon audio to your new bucket
3. Sign up for [JWPlayer's free plan](https://www.jwplayer.com/pricing/)
4. Download JWPlayer 7 (Self-Hosted) from the Players > Tools tab (and keep this tab open -- it's also where you get your Player license key)
5. Upload jwplayer.js and jwplayer.flash.swf to your S3 bucket
6. Change the permissions for all the files in your bucket ({file} > Permissions) to AllUsers:Read
7. Upload jwplayer.html to your bucket with the correct resource links and JWPlayer license key
8. Visit `https://s3.amazonaws.com/{bucket name}/jwplayer.html` and enjoy!

**Comment by isaacjwilliams** [comment]
We have decided not to use Cloudfront for now, since cache invalidation times are so high and because we have no need for Cloudfront services (yet).

**Comment by isaacjwilliams** [comment]
It looks like JWPlayer will support all the browsers and devices we care about. Consult the [JWPlayer browser and device support reference page](https://support.jwplayer.com/customer/portal/articles/1403653-browser-device-reference) for more detailed information.

Since this addresses the last unfinished to-do in the description, I will now close this issue! :grin:

**Comment by aiwilliams** [comment]
Great job @fomentia! I'll create another Issue for our next step 😄
