### ISSUE TITLE
Upload files to AWS S3 from a browser

### ISSUE THREAD

**Issue by aiwilliams** [wfth/online#2]
We need to allow content managers to upload content, and lots of it, on a single page and without having to send the media through our own servers. We will eventually need to inform our servers of the content, but this Issue is only about finding a solution to uploading a number of files from a single loaded HTML page.

- [x] Identify options for a HTML5/JS-based upload control/widget
- [x] Pick the one that you think is best and test each of the features below

Please list the options you consider along with links, pros and cons.

The primary features I think we'll need (you may learn of more, please note them):

- [x] Modern. We can require a modern browser since this will be the content manager UI.
- [x] Dynamically configured. Of course, we'll need to be able to give it temporary credentials to allow the browser to upload to S3.
- [x] Multiple instances on a page. The content manager will need to be able to pick a file per instance.
- [x] Ability to delete the associated resource. If the content manager deletes something in the UI, we need to be able to remove it from S3.
- [x] JS callbacks. We will need to be able to specify the resource name before it goes up to S3, monitor progress, know when it is finished and do all this with deletions also.
- [x] CSS styled.

Not required necessarily but worth considering:

- [x] Multiple files per upload. This would be Finder allowing for choosing a number of files, for example. There may be situations where the content manager wants to upload a lot of files.

**Comment by isaacjwilliams** [comment]
An HTML5 input tag with `type="file"` is modern, configurable, and CSS styled. Removing chosen files is easy with JavaScript. It supports a practically infinite number of instances per page. It has clear, easy-to-use JS callbacks. It even supports multiple files! Going with this is a no-brainer.

**Comment by isaacjwilliams** [comment]
To handle client interaction with S3, we'll use the [S3 JavaScript SDK](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html).

**Comment by isaacjwilliams** [comment]
Oops, I forgot to reference this issue in my commit message. I guess this comment will have to do!

See commit 5ee39cd06996f0daca080c2dd30609daa791c2f5

**Comment by aiwilliams** [comment]
We got this worked out. The code at https://github.com/wfth/online/commit/354e031af530aa81cb6cd5b5ca08f1e365ec4895 chronicles the changes necessary, for the most part. On the AWS bucket there must be the following CORS configuration:
```
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
  <CORSRule>
    <AllowedOrigin>http://localhost:3000</AllowedOrigin>
    <AllowedMethod>PUT</AllowedMethod>
    <AllowedMethod>POST</AllowedMethod>
    <AllowedMethod>DELETE</AllowedMethod>
    <MaxAgeSeconds>3000</MaxAgeSeconds>
    <ExposeHeader>ETag</ExposeHeader>
    <AllowedHeader>*</AllowedHeader>
  </CORSRule>
</CORSConfiguration>
```
