### ISSUE TITLE
Allow user to upload sermon series image

### ISSUE THREAD

**Issue by aiwilliams** [wfth/online#3]
We have the title and description. We need an image. I would suggest using the uuid approach that was used on the sermon audio and transcript upload.

**Comment by isaacjwilliams** [comment]
You say that we should "[use] the uuid approach that was used on the sermon audio and transcript upload". We put the sermon audio and transcript into `sermons/{uuid}/`. Where would we put the series graphic? I suggest something like `sermon_series/{series_uuid}/`. Then we can put the sermon audio and transcript into `sermon_series/{series_uuid}/sermons/{sermon_uuid}/`. What do you think?

Just FYI, my changes in f20d2f538bef4720416cbb12b2028a4b018bce72 upload the graphic to the bucket directly.

**Comment by aiwilliams** [comment]
@fomentia I love the nesting idea. Make it so 👍

**Comment by isaacjwilliams** [comment]
See c762673ccd7e9717e0ea5963b2ff9a82fb327a93
