### ISSUE TITLE
Create sermon series product on Shopify

### ISSUE THREAD

**Issue by aiwilliams** [wfth/online#4]
When a sermon series is created, create an item on Shopify. This should explore the API and discover how drafts/updating/publishing works.

**Comment by aiwilliams** [comment]
We have discovered a few things:

1. It is easy to connect to the Shopify API with the Ruby gem
2. We can use credentials for the API that are maintained within the settings of the shopify shop
3. We can create products and receive notifications (web hooks) when things change on shopify (though I don't know if we can do this without registering an app 🤔 )
4. We can, as a partner/developer, register an application and have it installed (embedded) into shopify shops so that shopify renders our app in an iframe
5. It is unclear how an app of that type is private (used only by a single shop)

- [x] Understand how it is that we can create an app and receive callbacks for a private shop
- [x] Create an app and experiment with adding it to a private shop

More to learn!

**Comment by isaacjwilliams** [comment]
You don't need a Shopify app to receive callbacks for a shop. Simply navigate to Settings > Notifications and set up a webhook for a specific event. You may already know this, but I just wanted to make sure. :blush:

**Comment by isaacjwilliams** [comment]
The changes I made in the Rails app to utilize Shopify webhooks are pretty simple. Just add a post route to `routes.rb` for Shopify to talk to and a corresponding action that extracts the relevant data from Shopify's JSON request.

I don't think we actually want to use the change I made to `application_controller.rb`. I intended this to be a temporary solution, for testing only. It allows all JSON requests to bypass Rails CSRF protection. Shopify provides a way to verify the integrity of requests, so I think that if we implement it, the problem will dissipate.

```
3 files changed, 13 insertions(+), 1 deletion(-)
app/controllers/application_controller.rb   |  2 +-
app/controllers/sermon_series_controller.rb | 10 ++++++++++
config/routes.rb                            |  2 ++

modified   app/controllers/application_controller.rb
@@ -1,3 +1,3 @@
 class ApplicationController < ActionController::Base
-  protect_from_forgery with: :exception
+  protect_from_forgery with: :null_session, if: Proc.new { |c| c.request.format == 'application/json' }
 end
modified   app/controllers/sermon_series_controller.rb
@@ -24,6 +24,16 @@ class SermonSeriesController < ApplicationController
     redirect_to action: "index"
   end
 
+  def shopify_create
+    sermon_series = SermonSeries.new
+
+    sermon_series.title = params[:title]
+    sermon_series.description = params[:body_html]
+    sermon_series.released_on = params[:created_at]
+
+    sermon_series.save
+  end
+
   private
 
   def sermon_series_params
modified   config/routes.rb
@@ -1,4 +1,6 @@
 Rails.application.routes.draw do
+  post 'sermon_series/shopify_create'
+
   resources :sermon_series do
     resources :sermons, shallow: true
   end
```

**Comment by isaacjwilliams** [comment]
Ok, so, I started work on a Shopify embedded app. Here goes the explaining... :sweat: 

An embedded app provides special functionality in the Shopify admin UI. Using Shopify's [embedded app SDK](https://help.shopify.com/api/sdks/merchant-apps/embedded-app-sdk), we can "access and customize many native GUI features". Unfortunately, private apps cannot use the embedded app SDK! The [solution to this problem](https://ecommerce.shopify.com/c/shopify-apis-and-technology/t/embedded-private-apps-255723), according to "Shopify Experts", is simply to create (but not publish) a public app.

Because Shopify sees the semi-private embedded app as public, simple authentication options (such as the aptly-named [*private authentication*](https://help.shopify.com/api/getting-started/authentication/private-authentication)) are not available. Alas! Ours is forced to act like an app from the Shopify app store and use OAuth. Clear instructions on [how to use OAuth with Shopify](https://help.shopify.com/api/getting-started/authentication/oauth) are provided in the docs. The Rails code necessary to support the OAuth handshake will be committed by yours truly sometime soon!

**Comment by isaacjwilliams** [comment]
According to Shopify, we should use the `shopify_app` gem, which "includes a Rails Engine and generators for writing Rails applications using the Shopify API". It also "provides a SessionsController and all the required code for authenticating with a shop via Oauth". This will make building an embedded app much easier!

Unfortunately, the code I wrote for OAuth only provides us with an offline access token, which won't help us in building an embedded app (embedded apps require online access tokens). Offline access tokens are good for background tasks and webhooks, while online access tokens are tied to a specific user's web session and are required for embedded apps (pretty obviously). Visit [Shopify's OAuth docs](https://help.shopify.com/api/getting-started/authentication/oauth#api-access-modes) to read more about the two different types of access tokens. The Shopify gem handles the session management of an embedded app.

Ugh. My code is already obsoleted. What a "waste" of time.

**Comment by aiwilliams** [comment]
> Ugh. My code is already obsoleted. What a "waste" of time.

Actually, you now understand better what will be done by the Ruby Gem! You've also learned more about how this whole thing hangs together; that is valuable knowledge.

It is very important to remember that you cannot change the past but you can use what you learn from the past in the future. Every project will have actual and felt losses. The question is whether we grow stronger through them or not 😁

**Comment by isaacjwilliams** [comment]
@aiwilliams I figured you would say that, which is why I put *waste* in quotations. 🙂

**Comment by aiwilliams** [comment]
We are successfully using the shopify_gem https://github.com/wfth/online/pull/8.

Considering the mode of the project at this time, when we are spiking through a number of things to learn how to build a Shopify app and customize things and whatnot, and considering the fact that we know how to create Products through the API and listen to webhooks, and considering that we need more specific tasks, I think we can call this one done.
