### ISSUE TITLE
Work out a way to receive web hooks from Shopify on localhost

### ISSUE THREAD

**Issue by aiwilliams** [wfth/online#5]
During development, we'll want to be able to receive web hooks and otherwise develop our custom app in a local environment. https://ngrok.com/ looks promising.

**Comment by isaacjwilliams** [comment]
ngrok is awesome! However, to use it for Shopify webhooks, we'll have to pay for the basic plan (5$ per month, paid annually).

Shopify webhooks work by sending POST requests to your server's URL. Thus, they rely on a consistent URL (pretty obvious). ngrok allows for specifying your subdomain (`ngrok http -subdomain=wfth 3000`), but to do so you must be a paying user. :sob:

**Comment by isaacjwilliams** [comment]
One way to get around this problem is to update the webhook's URL every time you restart ngrok. Obviously this isn't ideal, but it's working as a hack for now.

I will investigate other tunnel options. Too bad; ngrok is quite nice.

**Comment by isaacjwilliams** [comment]
Wee! [localtunnel](https://github.com/localtunnel/localtunnel) allows users to set custom subdomains for free. localtunnel has 4,157 stars on Github, so it doesn't seem shady. :man_shrugging:

Free software often comes with non-monetary fees. In localtunnel's case, this cost seems to be a somewhat slower connection than ngrok.

**Comment by isaacjwilliams** [comment]
I've created the "needs review" label so that I can filter issues without closing any. I don't want to actually close issues I consider finished because they need a final review from da big man (as the label's title suggests). :grin:

**Comment by aiwilliams** [comment]
Yah, localtunnel looks perfect! Please add a README.md to the root of the project with a link to that tool and a brief explanation of its purpose. That can close this issue. Thanks @fomentia!
